config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('search.urls'))
]

search/urls.py
from django.urls import path
from . import views


app_name = 'main'
urlpatterns = [
    path('', views.SearchView.as_view(), name='search'),
]

search/models.py
from django.db import models

# Create your models here.

search/forms.py
import json

from django import forms

def get_info():
    with open('search/json/info.json', 'r') as f:
        info = json.load(f)
    return info


class SearchForm(forms.Form):
    names = get_info().keys()
    choices = ((value, name) for value, name in zip(names, names))
    q = forms.CharField(label='タイトル', max_length=200, required=True)
    name = forms.ChoiceField(label='どのサービスを検索するか', required=True, choices=choices, widget=forms.RadioSelect(
        attrs={
            'class': 'btn-check',
            'auto-complete': 'off'
        }
    ))

search/views.py
import requests
import json
from django.views import generic

from .forms import SearchForm



# リクエスト先を動的に指定 apiをjson形式で取得(クラス内部で呼び出す)
def get_api_data(name, keyword):

    with open('search/json/info.json', 'r') as f:
        info = json.load(f)

        # Qiitaが選択されたとき
        if name == 'Qiita':
            url = info[name]['url']
            params = {
                'per_page': 100,
                'query': keyword
            }

            result = json.loads(requests.get(url, params).text)

        # GitHubが選択されとき
        elif name == 'GitHub':
            url = info[name]['url']
            params = {
                'per_page': 100,
                'q': keyword
            }

            result = json.loads(requests.get(url, params).text)['items']

        else:
            '''error handling'''
            pass

    return result


class SearchView(generic.ListView):
    context_object_name = 'data'

    def get_queryset(self):
        keyword = self.request.GET.get('q', default=None)
        name = self.request.GET.get('name')

        if keyword:
            queryset = get_api_data(name, keyword)
            return queryset

    # 検索フォームをレンダリング フォーム入力値をページ更新後も保持
    def get_context_data(self, **kwargs):
        if self.request.GET:
            form = SearchForm(initial={
                'q': self.request.GET.get('q'),
                'name': self.request.GET.get('name')
            })
        else:
            form = SearchForm
        keyword = self.request.GET.get('q', default=None)

        context = super().get_context_data(**kwargs)
        context['form'], context['keyword'] = (form, keyword)
        return context

    # nameの値によってtemplate_nameを動的に指定
    def get_template_names(self):
        name = self.request.GET.get('name', default=None)
        if name:
            template_name = f'main/sch{name}.html'
        else:
            template_name = 'main/search.html'
        return [template_name]

    '''NEXT --> pagenation機能実装 後々できたらでもいっか。'''

templates/common/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- Bootstrap.css読み込み -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
  <!-- --------------------- -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <title>StockR</title>
</head>

<body style="padding-top:4.5rem;">

  <!-- ========== MAIN CONTENT ========== -->
  <main>
    <div class="container my-5 mx-auto">
      {% block content %}
      {% endblock%}
    </div>
  </main>
  <!-- ========== END MAIN CONTENT ========== -->

  <!-- jQuery読み込み -->
  <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
  <!-- Bootstrapのjs読み込み -->
  <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>

</html>

templates/common/pagenateUI.html
<div class="pagination">
  <span class="step-links">
    {% if page_obj.has_previous %}
    <!-- 現在よりも前のページが存在する場合 -->
    <a href="?page=1">&laquo; 先頭</a>
    <a href="?page={{ page_obj.previous_page_number }}">前へ</a>
    {% endif %}

    <span class="current">
      <!-- 現在のページ番号と、全ページ数を表示 -->
      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
    </span>

    {% if page_obj.has_next %}
    <!-- 現在よりも後のページが存在する場合 -->
    <a href="?page={{ page_obj.next_page_number }}">次へ</a>
    <a href="?page={{ page_obj.paginator.num_pages }}">最後 &raquo;</a>
    {% endif %}
  </span>
</div>

templates/common/searchForm.html
{% load widget_tweaks %}

<div class="text-center mb-5 mx-md-auto col-md-8">
  <form method="get" action="{% url 'main:search' %}">
    <div>
      {% render_field form.q type='search' class='form-control rounded-pill mb-3 py-2' autocomplete='off' placeholder='キーワード または オプション を入力' %}
      {% for radio in form.name %}
      {{ radio.tag }}
      <label for="{{ radio.id_for_label }}" class="btn btn-outline-secondary rounded-pill btn-sm mx-3">
        {{radio.choice_label }}
      </label>
      {% endfor %}
    </div>
    <button type="submit" style="display: none;"></button><!-- 非表示 -->
  </form>
</div>

templates/main/schGitHub.html
{% extends 'common/base.html' %}
{% load widget_tweaks %}

{% block content %}

{% include 'common/searchForm.html' %}

<div class="list">
  {% for datum in data %}
  <div class="list-item p-3 m-3 bg-white rounded shadow">
    <div> <!-- name -->
      <a class="text-decoration-none fs-5" href="{{ datum.html_url }}">{{ datum.full_name }}</a>
    </div>
    <div> <!-- topics -->
    {% for topic in datum.topics %}
      <a class="text-decoration-none small text-dark me-2 px-1 py-1 rounded-pill" href="#" style="background-color: #dfdfdf;">{{ topic }}</a>
    {% endfor %}
    </div>
    <div class="pt-2"> <!-- description -->
      <p class="my-1 mb-0 text-secondary text-small">{{ datum.description|truncatechars:100 }}</p>
    </div>
    <div class="text-muted d-flex flex-wrap small pt-2">
      <div class="fw-bold me-3"> <!-- stargazers -->
        ☆ {{ datum.stargazers_count }}
      </div>
      <div class="me-3"> <!-- lang -->
        lang: {{ datum.language }}
      </div>
      <div class="me-3"> <!-- created time -->
        投稿日:{{ datum.created_at }}                             <!-- なんでフォーマットできんのじゃー -->
      </div>                                                    <!-- template filter のdateが使えない -->
      <div class="me-3"> <!-- updated time -->                  <!-- 指定するとなぜか空文字になっちゃう -->
        更新日:{{ datum.updated_at }}                             <!-- わからなすぎるから後回しで。さよならエレジー -->
      </div>
    </div>
  </div>
  {% empty %}
  <div>
    <p>「{{ keyword }}」に一致する投稿は見つかりませんでした。</p>
  </div>
  {% endfor %}
</div>

{% include 'common/pagenateUI.html' %}

{% endblock %}

templates/main/schQiita.html
{% extends 'common/base.html' %}
{% load widget_tweaks %}

{% block content %}

{% include 'common/searchForm.html' %}

<div class="list">
  {% for datum in data %}
  <div class="list-item p-3 m-3 bg-white rounded shadow">
    <div> <!-- title -->
      <a class="text-decoration-none fs-5" href="{{ datum.url }}">{{ datum.title }}</a>
    </div>
    <div> <!-- tags -->
    {% for tag in datum.tags %}
      <a class="text-decoration-none small text-dark me-2 px-1 py-1 rounded-pill" href="#" style="background-color: #dfdfdf;">{{ tag.name }}</a>
    {% endfor %}
    </div>
    <div class="pt-2"> <!-- body -->
      <p class="my-1 mb-0 text-secondary text-small">{{ datum.body|truncatechars:100 }}</p>
    </div>
    <div class="text-muted d-flex flex-wrap small pt-2">
      <div class="fw-bold me-3"> <!-- LGMT -->
        LGMT {{ datum.likes_count }}
      </div>
      <div class="me-3"> <!-- user name -->
        {{ datum.user.name }}(@{{ datum.user.id }})
      </div>
      <div class="me-3"> <!-- created time -->
        投稿日:{{ datum.created_at }}                             <!-- なんでフォーマットできんのじゃー -->
      </div>                                                    <!-- template filter のdateが使えない -->
      <div class="me-3"> <!-- updated time -->                  <!-- 指定するとなぜか空文字になっちゃう -->
        更新日:{{ datum.updated_at }}                             <!-- わからなすぎるから後回しで。さよならエレジー -->
      </div>
    </div>
  </div>
  {% empty %}
  <div>
    <p>「{{ keyword }}」に一致する投稿は見つかりませんでした。</p>
  </div>
  {% endfor %}
</div>

<!-- {% include 'common/pagenateUI.html' %} -->

{% endblock %}

templates/main/search.html
{% extends 'common/base.html' %}


{% block content %}

{% include 'common/searchForm.html' %}

<div class="text-center">
  <div class="pb-5">
    <b>キーワードを入力し、検索対象とするサービス名を一つ選択してください。<br>検索には各種サービスの検索オプションも使用可能です。</b>
  </div>
  <div>
    <p>検索オプションを確認する</p>
    <a href="https://help.qiita.com/ja/articles/qiita-search-options">Qiita</a><br>
    <a href="https://docs.github.com/ja/search-github/searching-on-github/searching-for-repositories">GitHub:repo</a>
  </div>
</div>

{% endblock %}